[package]
name = "bevy_heavy"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Joona Aalto <jondolf.dev@gmail.com>"]
description = "Mass property computation for Bevy's geometric primitives."

[features]
default = []

# Enable reflection using `bevy_reflect`.
bevy_reflect = ["dep:bevy_reflect"]

# Enable data serialization/deserialization using `serde`.
serialize = ["dep:serde", "bevy_math/serialize"]

# Enable `approx` for to approximate floating point equality comparisons and assertions for types.
approx = ["dep:approx", "bevy_math/approx"]

[dependencies]
bevy_math = { version = "0.14", default-features = false, features = [
    "approx",
] }

# Serialization
bevy_reflect = { version = "0.14", default-features = false, optional = true }
serde = { version = "1.0.197", default-features = false, optional = true }

approx = { version = "0.5", optional = true }

[dev-dependencies]
approx = "0.5"
